### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by 0xfffffff0075e2040** [kbhomes/libswitchui#1]
Could somebody make a example, including a example of printing text on the right side of the screen? maybe update the existing example and add a header and a small text block with the lorem ipsum text. Would definitely use this.

**Comment by FancyFurret** [comment]
This library was actually created for moonlight-switch. If you look at that repo you can find out how to render text, buttons, etc. https://github.com/kbhomes/moonlight-switch/tree/master/src/ui
